keys:
  - &Truman age1ryvy7qla9uxjpcw9hsz5y3ycejgfmldn7hlvptwu9rslgj2693rqmk2tfk
  - &Truman_backup age1ry6l8lwhkqg64z9543yqhua2fy97j3gennsxenm5pd0kqtfghfcq6zgdcy
creation_rules:
  - path_regex: hosts\/Truman\/secrets\/.*\.sops(?:\.yaml)*$
    key_groups:
      - age:
          - *Truman
          - *Truman_backup
