# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  switch:
    desc: Build and apply the system configuration
    cmds:
      - sudo darwin-rebuild switch --flake .#{{- .HOSTNAME -}} {{- .CLI_ARGS }}

  update:
    desc: Run flake update (specify an argument after '--' for updating a single package)
    cmds:
      - nix flake update {{ .CLI_ARGS }}

  gc:
    desc: Garbage collect
    cmds:
      # garbage collect all unused nix store entries(system-wide)
      - sudo nix-collect-garbage --delete-older-than 45d
      # garbage collect all unused nix store entries(for the user - home-manager)
      # https://github.com/NixOS/nix/issues/8508
      - nix-collect-garbage --delete-older-than 45d

  fmt:
    desc: Format all nix files
    cmds:
      - nix fmt

  repl:
    desc: Run a REPL shell for the flake
    cmds:
      - nix repl -f flake:nixpkgs

  macos_install_git:
    desc: Install git
    cmds:
      - xcode-select --install
    status:
      - xcode-select --print-path &>/dev/null

  macos_install_nix:
    desc: Install nix
    cmds:
      - curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
    status:
      - nix --version &>/dev/null &>/dev/null

  macos_install_brew:
    desc: Install Homebrew
    cmds:
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    status:
      - brew --version &>/dev/null

  prerequisites:
    desc: Install prerequisites
    cmds:
      - task: macos_install_git
      - task: macos_install_nix
      - task: macos_install_brew

  reinstall:
    desc: Reinstall nix-darwin
    cmds:
      - sudo nix run nix-darwin/nix-darwin-25.05 -- switch --flake .#{{ .HOSTNAME }}

  uninstall:
    desc: Remove nix darwin
    prompt:
      - This will remove nix-darwin. Are you sure?
    cmds:
      - sudo nix --extra-experimental-features "nix-command flakes" run nix-darwin#darwin-uninstaller

  uninstall_nix:
    desc: Remove nix
    prompt:
      - This will remove Nix entirely! Are you sure?
    cmds:
      - sudo -i nix-env --uninstall nix
