# https://taskfile.dev

version: "3"

vars:
  HOSTNAME: Truman

tasks:
  default:
    cmds:
      - task --list
    silent: true

  rebuild:
    desc: Build and apply the system configuration
    cmds:
      - darwin-rebuild switch --flake .#{{ .HOSTNAME }} {{ .CLI_ARGS }}

  update:
    desc: Run flake update (specify an argument after '--' for updating a single package)
    cmds:
      - nix flake update {{ .CLI_ARGS }}

  gc:
    desc: Garbage collect
    cmds:
      # garbage collect all unused nix store entries(system-wide)
      - sudo nix-collect-garbage --delete-older-than 45d
      # garbage collect all unused nix store entries(for the user - home-manager)
      # https://github.com/NixOS/nix/issues/8508
      - nix-collect-garbage --delete-older-than 45d

  fmt:
    desc: Format all nix files
    cmds:
      - nix fmt

  repl:
    desc: Run a REPL shell for the flake
    cmds:
      - nix repl -f flake:nixpkgs
# sudo -i nix-env --uninstall nix
